[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "sh -c 'celery -A core worker -l INFO --concurrency=${CELERY_WORKER_CONCURRENCY:-2}'"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 5
