[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "sh -c 'celery -A core purge -f && exec sleep infinity'"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 5
