# Generated by Django 5.2.15 on 2026-07-20 19:27

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


def create_default_plan_and_subscriptions(apps, schema_editor):
    barbershop_model = apps.get_model("barbershops", "Barbershop")
    subscription_plan_model = apps.get_model("billing", "SubscriptionPlan")
    subscription_model = apps.get_model("billing", "Subscription")
    plan, _ = subscription_plan_model.objects.get_or_create(
        code="barberhub",
        defaults={"name": "BarberHub", "amount": Decimal("79.90"), "trial_days": 30},
    )
    for barbershop in barbershop_model.objects.all().iterator():
        subscription_model.objects.get_or_create(
            barbershop_id=barbershop.id,
            defaults={"plan_id": plan.id, "status": "ACTIVE"},
        )


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('barbershops', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingWebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(max_length=20)),
                ('provider_event_id', models.CharField(max_length=150)),
                ('event_type', models.CharField(max_length=100)),
                ('payload', models.JSONField(default=dict)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('processing_error', models.CharField(blank=True, max_length=300)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('provider', 'provider_event_id'), name='unique_billing_provider_event')],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('currency', models.CharField(default='BRL', max_length=3)),
                ('trial_days', models.PositiveSmallIntegerField(default=30)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='billing_plan_amount_positive')],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('PENDING_CHECKOUT', 'Checkout pendente'), ('TRIAL', 'Período de teste'), ('ACTIVE', 'Ativa'), ('GRACE', 'Tolerância'), ('SUSPENDED', 'Suspensa'), ('CANCELED', 'Cancelada')], default='PENDING_CHECKOUT', max_length=24)),
                ('provider', models.CharField(choices=[('ASAAS', 'Asaas')], default='ASAAS', max_length=20)),
                ('provider_customer_id', models.CharField(blank=True, max_length=100)),
                ('provider_subscription_id', models.CharField(blank=True, db_index=True, max_length=100)),
                ('provider_checkout_id', models.CharField(blank=True, max_length=100)),
                ('external_reference', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('trial_days', models.PositiveSmallIntegerField(default=30)),
                ('trial_ends_at', models.DateTimeField(blank=True, null=True)),
                ('current_period_ends_at', models.DateTimeField(blank=True, null=True)),
                ('grace_ends_at', models.DateTimeField(blank=True, null=True)),
                ('next_billing_at', models.DateTimeField(blank=True, null=True)),
                ('last_payment_status', models.CharField(blank=True, max_length=50)),
                ('last_payment_at', models.DateTimeField(blank=True, null=True)),
                ('suspended_at', models.DateTimeField(blank=True, null=True)),
                ('canceled_at', models.DateTimeField(blank=True, null=True)),
                ('barbershop', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='barbershops.barbershop')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='billing.subscriptionplan')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BillingNotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(max_length=50)),
                ('status', models.CharField(default='PENDING', max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_logs', to='billing.subscription')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('subscription', 'kind'), name='unique_billing_notification_kind')],
            },
        ),
        migrations.RunPython(create_default_plan_and_subscriptions, migrations.RunPython.noop),
    ]
