# Generated by Django 5.2.15 on 2026-07-21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0002_subscription_provider_cycle_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="billingwebhookevent",
            name="dead_lettered_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="billingwebhookevent",
            name="dispatch_attempts",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="billingwebhookevent",
            name="last_dispatched_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="billingwebhookevent",
            name="last_processing_attempt_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="billingwebhookevent",
            name="next_dispatch_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="billingwebhookevent",
            name="processing_attempts",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name="SubscriptionPaymentCycle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("provider_payment_id", models.CharField(max_length=100)),
                ("grace_started_at", models.DateTimeField(blank=True, null=True)),
                ("succeeded_at", models.DateTimeField(blank=True, null=True)),
                (
                    "subscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_cycles",
                        to="billing.subscription",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="subscriptionpaymentcycle",
            constraint=models.UniqueConstraint(
                fields=("subscription", "provider_payment_id"),
                name="unique_sub_provider_payment",
            ),
        ),
        migrations.AddIndex(
            model_name="billingwebhookevent",
            index=models.Index(
                fields=[
                    "processed_at",
                    "dead_lettered_at",
                    "next_dispatch_at",
                    "id",
                ],
                name="billing_wh_recovery_idx",
            ),
        ),
    ]
