# Generated by Django 5.2.15 on 2026-07-21

from datetime import timedelta

import django.db.models.deletion
from django.db import migrations, models
from django.utils import timezone
from django.utils.dateparse import parse_datetime


PAYMENT_GRACE_EVENTS = {
    "PAYMENT_OVERDUE",
    "PAYMENT_REPROVED_BY_RISK_ANALYSIS",
}
PAYMENT_SUCCESS_EVENTS = {"PAYMENT_CONFIRMED", "PAYMENT_RECEIVED"}


def _provider_event_at(event):
    payload = event.payload
    if isinstance(payload, dict):
        value = payload.get("dateCreated")
        if isinstance(value, str):
            parsed = parse_datetime(value)
            if parsed is not None and timezone.is_aware(parsed):
                return parsed
    return event.processed_at or event.updated_at or event.created_at


def _set_first_cycle_timestamp(cycle, field_name, event_at):
    current = getattr(cycle, field_name)
    if event_at is not None and (current is None or event_at < current):
        setattr(cycle, field_name, event_at)
        cycle.save(update_fields=[field_name, "updated_at"])


def backfill_payment_cycles(apps, schema_editor):
    subscription_model = apps.get_model("billing", "Subscription")
    event_model = apps.get_model("billing", "BillingWebhookEvent")
    cycle_model = apps.get_model("billing", "SubscriptionPaymentCycle")

    subscriptions_by_provider_id = {}
    ambiguous_provider_ids = set()
    subscriptions = list(subscription_model.objects.all())
    for subscription in subscriptions:
        provider_id = subscription.provider_subscription_id
        if not provider_id:
            continue
        if provider_id in subscriptions_by_provider_id:
            ambiguous_provider_ids.add(provider_id)
        else:
            subscriptions_by_provider_id[provider_id] = subscription
    for provider_id in ambiguous_provider_ids:
        subscriptions_by_provider_id.pop(provider_id, None)

    event_types = PAYMENT_GRACE_EVENTS | PAYMENT_SUCCESS_EVENTS
    events = event_model.objects.filter(
        provider="ASAAS",
        processed_at__isnull=False,
        event_type__in=event_types,
    ).order_by("processed_at", "id")
    for event in events.iterator():
        payment = event.payload.get("payment") if isinstance(event.payload, dict) else None
        if not isinstance(payment, dict):
            continue
        payment_id = payment.get("id")
        provider_subscription_id = payment.get("subscription")
        subscription = subscriptions_by_provider_id.get(provider_subscription_id)
        if not isinstance(payment_id, str) or not payment_id or subscription is None:
            continue
        cycle, _ = cycle_model.objects.get_or_create(
            subscription_id=subscription.id,
            provider_payment_id=payment_id,
        )
        field_name = (
            "grace_started_at"
            if event.event_type in PAYMENT_GRACE_EVENTS
            else "succeeded_at"
        )
        _set_first_cycle_timestamp(cycle, field_name, _provider_event_at(event))

    for subscription in subscriptions:
        if subscription.grace_payment_id:
            cycle, _ = cycle_model.objects.get_or_create(
                subscription_id=subscription.id,
                provider_payment_id=subscription.grace_payment_id,
            )
            grace_started_at = (
                subscription.grace_ends_at - timedelta(days=7)
                if subscription.grace_ends_at is not None
                else subscription.updated_at
            )
            _set_first_cycle_timestamp(
                cycle,
                "grace_started_at",
                grace_started_at,
            )
        if subscription.last_payment_id:
            cycle, _ = cycle_model.objects.get_or_create(
                subscription_id=subscription.id,
                provider_payment_id=subscription.last_payment_id,
            )
            _set_first_cycle_timestamp(
                cycle,
                "succeeded_at",
                subscription.last_payment_at,
            )


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0002_subscription_provider_cycle_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="billingwebhookevent",
            name="dead_lettered_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="billingwebhookevent",
            name="dispatch_attempts",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="billingwebhookevent",
            name="last_dispatched_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="billingwebhookevent",
            name="last_processing_attempt_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="billingwebhookevent",
            name="next_dispatch_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="billingwebhookevent",
            name="processing_attempts",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name="SubscriptionPaymentCycle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("provider_payment_id", models.CharField(max_length=100)),
                ("grace_started_at", models.DateTimeField(blank=True, null=True)),
                ("succeeded_at", models.DateTimeField(blank=True, null=True)),
                (
                    "subscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_cycles",
                        to="billing.subscription",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="subscriptionpaymentcycle",
            constraint=models.UniqueConstraint(
                fields=("subscription", "provider_payment_id"),
                name="unique_sub_provider_payment",
            ),
        ),
        migrations.RunPython(backfill_payment_cycles, migrations.RunPython.noop),
        migrations.AddIndex(
            model_name="billingwebhookevent",
            index=models.Index(
                fields=[
                    "processed_at",
                    "dead_lettered_at",
                    "next_dispatch_at",
                    "id",
                ],
                name="billing_wh_recovery_idx",
            ),
        ),
    ]
