# Generated by Django 5.2.15 on 2026-07-21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0003_webhook_recovery_and_payment_cycles"),
    ]

    operations = [
        migrations.AddField(
            model_name="billingnotificationlog",
            name="claim_token",
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
    ]
