# Generated by Django 5.2.15 on 2026-07-21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0004_billingnotificationlog_claim_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="billingnotificationlog",
            name="email_snapshot",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
