# Generated by Django 5.2.15 on 2026-07-21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0005_billingnotificationlog_email_snapshot"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="regularization_checkout_claim",
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="subscription",
            name="regularization_checkout_id",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="subscription",
            name="regularization_checkout_state",
            field=models.CharField(
                choices=[
                    ("READY", "Pronto"),
                    ("CREATING", "Criando"),
                    ("CREATED", "Criado"),
                    ("PAID", "Pago"),
                ],
                default="READY",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="subscription",
            name="regularization_checkout_url",
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
