# Generated by Django 5.2.16 on 2026-07-21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0006_subscription_regularization_checkout"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="regularization_checkout_error",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="regularization_checkout_state",
            field=models.CharField(
                choices=[
                    ("READY", "Pronto"),
                    ("CREATING", "Criando"),
                    ("CREATED", "Criado"),
                    ("PAID", "Pago"),
                    ("RECONCILIATION_REQUIRED", "Reconciliação necessária"),
                ],
                default="READY",
                max_length=24,
            ),
        ),
        migrations.AddField(
            model_name="billingnotificationlog",
            name="dedupe_key",
            field=models.CharField(blank=True, default="", max_length=180),
        ),
        migrations.RemoveConstraint(
            model_name="billingnotificationlog",
            name="unique_billing_notification_kind",
        ),
        migrations.AddConstraint(
            model_name="billingnotificationlog",
            constraint=models.UniqueConstraint(
                fields=("subscription", "kind", "dedupe_key"),
                name="unique_billing_notification_dedupe",
            ),
        ),
    ]
