# Generated by Django 5.2.16 on 2026-07-21

from django.db import migrations, models


def backfill_known_legacy_checkout_references(apps, schema_editor):
    subscription_model = apps.get_model("billing", "Subscription")
    (
        subscription_model.objects.filter(
            regularization_checkout_state="CREATED",
        )
        .exclude(regularization_checkout_id="")
        .exclude(regularization_checkout_url="")
        .update(regularization_checkout_reference=models.F("external_reference"))
    )


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0007_regularization_reconciliation_and_notification_dedupe"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="regularization_checkout_claim_started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="subscription",
            name="regularization_checkout_reference",
            field=models.UUIDField(blank=True, editable=False, null=True, unique=True),
        ),
        migrations.RunPython(
            backfill_known_legacy_checkout_references,
            migrations.RunPython.noop,
        ),
    ]
