# Generated by Django 5.2.16 on 2026-07-21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0007_regularization_reconciliation_and_notification_dedupe"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="regularization_checkout_claim_started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="subscription",
            name="regularization_checkout_reference",
            field=models.UUIDField(blank=True, editable=False, null=True, unique=True),
        ),
    ]
