# Generated by Django 5.2.16 on 2026-07-21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_alter_user_email_alter_user_groups_and_more"),
        ("billing", "0008_regularization_attempt_reference_and_claim_started"),
    ]

    operations = [
        migrations.CreateModel(
            name="RegularizationEmailRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("email_hash", models.CharField(max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pendente"),
                            ("SENDING", "Enviando"),
                            ("SENT", "Enviado"),
                            ("FAILED", "Falhou"),
                            ("DISCARDED", "Descartado"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("attempts", models.PositiveSmallIntegerField(default=0)),
                (
                    "claim_token",
                    models.UUIDField(blank=True, editable=False, null=True),
                ),
                ("email_snapshot", models.JSONField(blank=True, null=True)),
                ("next_attempt_at", models.DateTimeField()),
                ("expires_at", models.DateTimeField()),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                (
                    "subscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="regularization_email_requests",
                        to="billing.subscription",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="billing_regularization_email_requests",
                        to="accounts.user",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="regularizationemailrequest",
            constraint=models.UniqueConstraint(
                fields=("subscription", "email_hash"),
                name="unique_regularization_email_request",
            ),
        ),
        migrations.AddIndex(
            model_name="regularizationemailrequest",
            index=models.Index(
                fields=["status", "next_attempt_at", "expires_at", "id"],
                name="billing_reg_email_recovery_idx",
            ),
        ),
    ]
