# Generated by Django 5.2.16 on 2026-07-22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0009_regularization_email_request"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="signup_checkout_state",
            field=models.CharField(
                choices=[
                    ("CREATING", "Criando"),
                    ("CREATED", "Criado"),
                    ("RECONCILIATION_REQUIRED", "Reconciliação necessária"),
                ],
                default="CREATING",
                max_length=24,
            ),
        ),
    ]
